version: 0.2
phases:
  build:
    commands:
      - echo "Zipping deployment package..."
      - git clone https://github.com/khajum7/tdms-dev.git
      - zip -r9 deployment_package.zip tdms-dev/*
artifacts:
  files: deployment_package.zip
