version: 0.2
phases:
  build:
    commands:
      - echo "Zipping deployment package..."
      - git clone https://github.com/khajum7/tdms-dev.git
      - zip -r9 deployment_package.zip tdms-dev/*
      
post_build:
  commands:
    - aws --version
    - echo "Deploying to Lambda..."
    - aws lambda update-function-code --function-name Testing-CICD --zip-file fileb://deployment_package.zip


artifacts:
  files: deployment_package.zip
